post:
  label: 文章设置
  items:
    share_type:
      name: share_type
      label: 文章分享组件
      type: select
      default: ''
      options:
        - value: ''
          label: '无'
        - value: addtoany
          label: addtoany
        - value: bdshare
          label: bdshare
        - value: sharejs
          label: sharejs
    donate_alipay:
      name: donate_alipay
      label: 支付宝捐赠二维码
      type: attachment
      placeholder: '二维码地址'
    donate_wechat:
      name: donate_wechat
      label: 微信捐赠二维码
      type: attachment
      placeholder: '二维码地址'
    mathjax_enable:
      name: mathjax_enable
      label: MathJax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: Default
      options:
        - value: Default
          label: Default
        - value: Coy
          label: Coy
        - value: Dark
          label: Dark
        - value: Okaidia
          label: Okaidia
        - value: Solarized Light
          label: Solarized Light
        - value: Tomorrow Night
          label: Tomorrow Night
        - value: Twilight
          label: Twilight
sidebar:
  label: 侧边栏
  items:
    profile_avatar_type:
      name: profile_avatar_type
      label: 头像形状
      type: select
      default: 'avatar_rounded'
      options:
        - value: avatar_rounded
          label: '圆形'
        - value: avatar_square
          label: '方形'
    profile_location:
      name: profile_location
      label: 地理位置
      type: text
      placeholder: '个人所在地'
    profile_follow_url:
      name: profile_follow_url
      label: 【关注我】按钮地址
      type: text
      placeholder: '默认为博客地址'
    sidebar_profile:
      name: sidebar_profile
      label: 侧边栏个人资料
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_categories:
      name: sidebar_categories
      label: 侧边栏分类
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_tagcloud:
      name: sidebar_tagcloud
      label: 侧边栏标签云
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_links:
      name: sidebar_links
      label: 侧边栏链接
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_recentpost:
      name: sidebar_recentpost
      label: 侧边栏最近文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_recentcomment:
      name: sidebar_recentcomment
      label: 侧边栏最近评论
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    sidebar_tags:
      name: sidebar_tags
      label: 侧边栏标签
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    social_github:
      name: social_github
      label: Github
      type: text
      placeholder: 'Github 用户名'
    social_qq:
      name: social_qq
      label: QQ
      type: text
      placeholder: 'QQ 号'
    social_weibo:
      name: social_weibo
      label: 微博
      type: text
      placeholder: '微博用户名'
    social_twitter:
      name: social_twitter
      label: Twitter
      type: text
      placeholder: 'Twitter 用户名'
    social_facebook:
      name: social_facebook
      label: Facebook
      type: text
      placeholder: 'Facebook 用户名'
    social_email:
      name: social_email
      label: Email
      type: text
      placeholder: '邮箱地址'
    social_telegram:
      name: social_telegram
      label: Telegram
      type: text
      placeholder: 'Telegram 用户名'
custom_links:
  label: 自定义链接
  items:
    links_top:
      name: links_top
      label: 顶部链接
      type: textarea
      default: '<a class="navbar-item" target="_blank" title="Download on GitHub" href="https://github.com/halo-dev/halo-theme-icarus">
                    <i class="fab fa-github"></i>
                </a>'
    links_footer:
      name: links_footer
      label: 底部链接
      type: textarea
      default: '<p class="control">
                    <a class="button is-white is-large" target="_blank" title="Creative Commons" href="https://creativecommons.org/">
                        <i class="fab fa-creative-commons"></i>
                    </a>
                </p>
                <p class="control">
                    <a class="button is-white is-large" target="_blank" title="Attribution 4.0 International" href="https://creativecommons.org/licenses/by/4.0/">
                        <i class="fab fa-creative-commons-by"></i>
                    </a>
                </p>'
slider_set:
  label: 轮播设置
  items:
    slider_enable:
       name: notice_enable
       label: 轮播开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    slider_json_enable:
       name: slider_json_enable
       label: 轮播JSON模式开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
       description: '根据json显示内容，灵活性强，若JSON模式和标签模式都开，优先显示JSON模式'
    slider_list_json_content:
       name: slider_json_content
       label: 轮播列表JSON内容
       type: textarea
       placeholder: '填入json格式[{id:int,title:string,thumbnail:String,url:string}]'
       description: '<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>格式复制：[{"id":0,"title":"标题","thumbnail":"图片链接","url":"跳转连接"}]'
    slider_side_json_content:
       name: slider_json_content
       label: 轮播附图JSON内容
       type: textarea
       placeholder: '填入json格式[{id:int,title:string,thumbnail:String,url:string}]'
       description: '<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>格式复制：[{"id":0,"title":"标题","thumbnail":"图片链接","url":"跳转连接"}]'
    slider_tag_enable:
       name: slider_tag_enable
       label: 轮播标签模式开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
       description: '根据文章的标签显示内容，灵活不强，只适用文章，若JSON模式和标签模式都开，优先显示JSON模式'
    slider_main_tag:
       name: slider_main_tag
       label: 【轮播列表】标签别名
       type: text
       placeholder: '默认为lunboliebiao'
       description: '自定义轮播图显示内容，对应文章标签别名,建议是英文字母'
    slider_right_tag:
       name: slider_right_tag
       label: 【轮播附图】标签别名
       type: text
       placeholder: '默认为lunbofutu'
       description: '自定义右侧图显示内容，对应文章标签别名,建议是英文字母'
view_set:
  label: 界面配置
  items:
    advert_enable:
       name: advert_enable
       label: Banner广告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    advert_title:
       name: advert_title
       label: Banner广告标题
       type: text
       placeholder: '广告标题'
    advert_pc_img:
       name: advert_pc_img
       label: BannerPC端广告图
       type: attachment
       placeholder: '广告图'
    advert_mobile_img:
       name: advert_mobile_img
       label: Banner移动端广告图
       type: attachment
       placeholder: '广告图'
    advert_href:
       name: advert_href
       label: Banner广告链接
       type: text
       placeholder: '广告链接'
       default: '#none'
    notice_enable:
       name: notice_enable
       label: 公告开关
       type: radio
       data-type: bool
       default: false
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_tag:
       name: notice_tag
       label: 公告标签别名
       type: text
       placeholder: '默认为notice'
       description: '定义公告显示内容，对应文章标签别名,建议是英文字母'
    notice_navbar_enable:
       name: notice_navbar_enable
       label: 公告栏导航开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    notice_navbar:
       name: notice_navbar
       label: 公告栏导航代码
       type: textarea
       placeholder: '请输入代码'
       default: '<a href="https://www.mumusur.com/www/designer-navbar/index.html" target="_blank">
				     <i class="fas fa-paint-brush"></i>&nbsp;&nbsp;设计师导航网站
			     </a>
                 <a href="https://www.mumusur.com/journals" target="_blank">
				     <i class="fas fa-circle-o-notch fa-spin"></i>&nbsp;&nbsp;心情
			     </a>
                 <a href="https://www.mumusur.com/photos" target="_blank">
				     <i class="fas fa-photo"></i>&nbsp;&nbsp;图库
			     </a>
			     <a href="https://www.mumusur.com/s/about.html" target="_blank">
				     <i class="fas fa-coffee"></i>&nbsp;&nbsp;关于
			     </a>
          	     <a href="https://www.mumusur.com/s/guestbook.html" target="_blank">
				     <i class="fas fa-comments"></i>&nbsp;&nbsp;留言板
			     </a>'
footer_set:
  label: 页脚设置
  items:
    footer_logo:
      name: footer_logo
      label: 页脚LOGO
      type: attachment
      placeholder: '页脚LOGO'
    footer_logo_memo:
      name: footer_logo_memo
      label: 页脚LOGO描述文字
      type: textarea
      placeholder: '页脚LOGO描述文字'
      default: '<p>一个资源丰富的平台</p>
                <p>在线时间：10:00-17:00 22:00-24:00</p>
                <p>电子邮箱：996052600@QQ.COM</p>'
    footer_more_links:
      name: footer_more_links
      label: 链接集
      type: textarea
      placeholder: '链接集格式为json'
      description: '<a href="http://www.bejson.com/" target="_blank">JSON工具</a><br/>格式复制：[{"id":0,"icon":"图标","title":"标题","url":"跳转连接"}]'
    footer_qr_01:
      name: footer_qr_01
      label: 二维码01
      type: attachment
      placeholder: '二维码01'
    footer_qr_01_desc:
       name: footer_qr_01_desc
       label: 二维码01描述
       type: text
       placeholder: '二维码01描述'
    footer_qr_02:
      name: footer_qr_02
      label: 二维码02
      type: attachment
      placeholder: '二维码02'
    footer_qr_02_desc:
       name: footer_qr_02_desc
       label: 二维码02描述
       type: text
       placeholder: '二维码02描述'
    footer_qr_03:
      name: footer_qr_03
      label: 二维码03
      type: attachment
      placeholder: '二维码03'
    footer_qr_03_desc:
       name: footer_qr_03_desc
       label: 二维码03描述
       type: text
       placeholder: '二维码03描述'
    footer_flinks_enable:
       name: footer_flinks_enable
       label: 页脚友情链接开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_flinks_alias:
       name: footer_flinks_alias
       label: 匹配分组名
       type: text
       placeholder: '匹配分组名，默认友情链接'
    footer_flinks_name:
       name: footer_flinks_name
       label: 友链申请名
       type: text
       placeholder: '点击申请友链'
       default: '点击申请友链'
    footer_flinks_url:
       name: footer_flinks_url
       label: 友链申请地址
       type: text
       placeholder: '友链申请地址'
       default: 'https://www.mumusur.com/s/flinks.html'
    footer_desc_enable:
       name: footer_desc_enable
       label: 页脚描述开关
       type: radio
       data-type: bool
       default: true
       options:
         - value: true
           label: 开启
         - value: false
           label: 关闭
    footer_desc:
       name: footer_desc
       label: 页脚描述
       type: textarea
       placeholder: '页脚描述信息(如版权信息)'